MvcPersonalProject.UI/Controllers/ServiceController.cs
using MvcPersonalProject.BLL;
using MvcPersonalProject.Entity;
using MvcPersonalProject.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MvcPersonalProject.UI.Controllers
{
    [Auth]
    public class ServiceController : Controller
    {
        private ServiceManager serviceManager = new ServiceManager();

        public ActionResult Index()
        {
            return View(serviceManager.ListQueryable().OrderByDescending(x=>x.CreatedOn).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = serviceManager.Find(x => x.Id == id.Value);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Services services = serviceManager.Find(x => x.Id == id.Value);
            if (services == null)
            {
                return HttpNotFound();
            }
            return View(services);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]

        public ActionResult Edit(Services services)
        {
            if (ModelState.IsValid)
            {
                Services s = serviceManager.Find(x => x.Id == services.Id);
                s.Text = services.Text;
                s.Title = services.Title;
                serviceManager.Update(s);
                return RedirectToAction("Index");
            }
            return View(services);
        }
    }
}

MvcPersonalProject.UI/Views/Service/Details.cshtml
@model MvcPersonalProject.Entity.Services

@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Text)
            </dt>

            <dd>
                @Html.Raw(Model.Text)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedOn)
            </dd>

        </dl>
    </div>
</div>
<div class="col-md-12 text-right">
    <a href="/Service/Edit/@Model.Id" class="btn btn-warning" title="Güncelle"><i class="fa fa-edit mr-2"></i> Güncelle</a>
    <a href="/Service/Index" class="btn btn-default" title="Geri Dön"><i class="fa fa-angle-double-left mr-2"></i> Geri Dön</a>
</div>

MvcPersonalProject.UI/Views/Service/Edit.cshtml
@model MvcPersonalProject.Entity.Services

@{
    ViewBag.Title = "Güncelleme";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "Service", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(false)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label" })
                        @*@Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "ckeditor" } })*@
                        <textarea name="Text" class="ckeditor form-control">@Model.Text</textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        <button type="submit" class="btn btn-success"> <i class="fa fa-save"></i>Kaydet</button>
                        <a href="/Service/Index" class="btn btn-danger"><i class="fa fa-angle-double-left"></i>İptal</a>
                    </div>
                </div>

            </div>
        }
    </div>
</div>

@*<script type="text/javascript">
    CKEDITOR.replace('editor')
</script>*@

MvcPersonalProject.UI/Views/Service/Index.cshtml
@model IEnumerable<MvcPersonalProject.Entity.Services>

@{
    ViewBag.Title = "Hizmetler";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<table class="table table-bordered table-striped table-hover table-sm">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.Raw(item.Text)
            </td>
            <td>
                <a href="/Service/Edit/@item.Id" title="Güncelle" class="btn btn-warning"><i class="fa fa-edit mr-2"> Güncelle</i></a>
                <a href="/Service/Details/@item.Id" title="Detay" class="btn btn-default"> <i class="fa fa-search mr-2"> Detay</i></a>
            </td>
        </tr>
    }

</table>