MvcPersonalProject.UI/Controllers/AdminProcessController.cs
using MvcPersonalProject.BLL;
using MvcPersonalProject.Common.Helpers;
using MvcPersonalProject.Entity;
using MvcPersonalProject.Entity.ValueObjects;
using MvcPersonalProject.UI.Filters;
using MvcPersonalProject.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace MvcPersonalProject.UI.Controllers
{    
    public class AdminProcessController : Controller
    {
        private UserManager userManager = new UserManager();

        [Auth]
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var pass = Crypto.Hash(model.Password.ToString(), "MD5");
                User user = userManager.Find(x => x.Email == model.Email && x.Password == pass);
                if (user == null)
                {
                    ViewBag.LoginFail = "Lütfen email ayada şifrenizi tekrar kontrol ediniz";
                    return View(model);
                }
                CurrentSession.Set<User>("login", user);
                return RedirectToAction("Index");
            }
            ViewBag.LoginFail = "Lütfen email ayada şifrenizi tekrar kontrol ediniz";
            return View(model);
         }

        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }

        public ActionResult ForgetPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ForgetPassword(ForgetPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = userManager.Find(x => x.Email == model.Email);
                if (user == null)
                {
                    ViewBag.EmailNotIsValid = "Lütfen geçerli bir email adresi giriniz.";
                    return View(model);
                }
                int newnumber = 0;
                Random rnd = new Random();
                newnumber = rnd.Next();
                user.Password = Crypto.Hash(newnumber.ToString(), "MD5");
                userManager.Update(user);
                string body = $"Merhaba {user.Name} {user.Surname}; <br> <br> Yeni Şİfre : {newnumber}";
                MailHelper.SendMail(body, user.Email, "Welat BARAN Kişisel Web Sayfası - Yeni Şİfre Talebi", true);
                ViewBag.ForgetPassSuccess = "Yeni şifreniz email adresinize başarılı bir şekilde gönderilmiştir. ";
                return View("ForgetPassword");
            }
            ViewBag.EmailNotIsValid = "Lütfen geçerli bir email adresi giriniz.";
            return View(model);
        }
    }
}

MvcPersonalProject.UI/Views/AdminProcess/ForgetPassword.cshtml
@model MvcPersonalProject.Entity.ValueObjects.ForgetPasswordViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Şifremi Unuttum</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="~/Content/login.css" rel="stylesheet" />
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <!-- Icon -->
            <div class="fadeIn first">
                <img src="~/Image/logo.png" id="logo" alt="" width="150" height="150" />
            </div>
            @{
                if (ViewBag.ForgetPassSuccess != null)
                {
                    <h4 style="color:green" class="fa fa-check-circle"> @ViewBag.Success</h4>
                }
                else if (ViewBag.EmailNotIsValid != null)
                {
                    <h4 style="color:red" class="fa fa-remove"> @ViewBag.Fail</h4>
                }
            }
            @using (Html.BeginForm("ForgetPassword", "AdminProcess", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <!-- Login Form -->
                <input type="email" id="Email" class="fadeIn second form-control" name="Email" placeholder="email...">
                <input type="submit" class="fadeIn fourth" value="Şifre Gönder">
                <a href="/AdminProcess/Login" class="btn btn-warning"> <i class="fa fa-chevron-left"></i> Anasayfaya Dön!</a>
            }

        </div>
    </div>
</body>
</html>

MvcPersonalProject.UI/Views/AdminProcess/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">content_copy</i>
                    </div>
                    <p class="card-category">Hizmet Kategori Alanları</p>
                    <h3 class="card-title">
                        4
                    </h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        Detay...
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">store</i>
                    </div>
                    <p class="card-category">Yapılan Projeler</p>
                    <h3 class="card-title">7</h3>
                </div>
                <div class="card-footer">
                    <div class="stats">
                        Detay...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MvcPersonalProject.UI/Views/AdminProcess/Login.cshtml
@model MvcPersonalProject.Entity.ValueObjects.LoginViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Giriş Sayfası</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="~/Content/login.css" rel="stylesheet" />
</head>
<body>

    <div class="wrapper fadeInDown">
        <div id="formContent">
            <!-- Tabs Titles -->
            <!-- Icon -->
            <div class="fadeIn first">
                <img src="~/Image/logo.png" id="logo" alt="" width="150" height="150" />
            </div>
            @if (ViewBag.LoginFail != null)
            {
            <h4 style="color:red" class="fa fa-remove"> @ViewBag.Fail</h4>
            }
            @using (Html.BeginForm("Login", "AdminProcess", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <!-- Login Form -->
                <input type="email" id="Email" class="fadeIn second form-control" name="Email" placeholder="email...">
                <input type="password" id="Password" class="fadeIn third form-control" name="Password" placeholder="şifre...">
                <input type="submit" class="fadeIn fourth" value="Giriş">
            }

            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="/AdminProcess/ForgetPassword">Şifremi Unuttum?</a>
            </div>

        </div>
    </div>
</body>
</html>