MvcPersonalProject.UI/Controllers/ProjectDoneController.cs
using MvcPersonalProject.BLL;
using MvcPersonalProject.Entity;
using MvcPersonalProject.UI.Filters;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace MvcPersonalProject.UI.Controllers
{
    [Auth]
    public class ProjectDoneController : Controller
    {
        private ProjectDoneManager projectDoneManager = new ProjectDoneManager();
        private ServiceManager serviceManager = new ServiceManager();

        public ActionResult Index()
        {
            return View(projectDoneManager.ListQueryable().Include("Services").OrderByDescending(x=>x.CreatedOn).ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsDones projectsDones = projectDoneManager.Find(x => x.Id == id.Value);
            if (projectsDones == null)
            {
                return HttpNotFound();
            }
            return View(projectsDones);
        }

        [HttpGet]
        public ActionResult Create()
        {
            //IEnumerable<SelectListItem> list = (from k in serviceManager.List()
            //                             select new SelectListItem
            //                             {
            //                                 Text = k.Title,
            //                                 Value = k.Id.ToString()
            //                             }).ToList();
            //ViewBag.ServicesId = list;
            ViewBag.ServicesList = new SelectList(serviceManager.List(), "Id", "Title");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ProjectsDones projectsDones , HttpPostedFileBase Image1, HttpPostedFileBase Image2, HttpPostedFileBase Image3)
        {
            ModelState.Remove("CreatedOn");
            ModelState.Remove("ModifiedOn");
            if (ModelState.IsValid)
            {
                if (Image1 != null &&
                      (Image1.ContentType == "image/jpeg" ||
                       Image1.ContentType == "image/jpg" ||
                       Image1.ContentType == "image/png"))
                {
                    string filename1 = $"{projectsDones.ProjectName}_Image1.{Image1.ContentType.Split('/')[1]}";
                    Image1.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename1}"));
                    projectsDones.Image1 = filename1;
                }
                if (Image2 != null &&
                      (Image2.ContentType == "image/jpeg" ||
                       Image2.ContentType == "image/jpg" ||
                       Image2.ContentType == "image/png"))
                {
                    string filename2 = $"{projectsDones.ProjectName}_Image2.{Image2.ContentType.Split('/')[1]}";
                    Image2.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename2}"));
                    projectsDones.Image2 = filename2;
                }
                if (Image3 != null &&
                      (Image3.ContentType == "image/jpeg" ||
                       Image3.ContentType == "image/jpg" ||
                       Image3.ContentType == "image/png"))
                {
                    string filename3 = $"{projectsDones.ProjectName}_Image3.{Image3.ContentType.Split('/')[1]}";
                    Image3.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename3}"));
                    projectsDones.Image3 = filename3;
                }

                projectDoneManager.Insert(projectsDones);
                return RedirectToAction("Index");
            }
            ViewBag.ServicesList = new SelectList(serviceManager.List(), "Id", "Title",projectsDones.ServicesId);
            return View(projectsDones);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            //ViewBag.ServicesId = (from k in serviceManager.List()
            //                      select new SelectListItem
            //                      {
            //                          Text = k.Title,
            //                          Value = k.Id.ToString()
            //                      }).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProjectsDones projectsDones = projectDoneManager.Find(x => x.Id == id.Value);
            if (projectsDones == null)
            {
                return HttpNotFound();
            }
            ViewBag.ServicesId = new SelectList(serviceManager.List(), "Id", "Title", projectsDones.ServicesId);
            return View(projectsDones);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ProjectsDones projectsDones, HttpPostedFileBase Image1, HttpPostedFileBase Image2, HttpPostedFileBase Image3)
        {
            ModelState.Remove("ModifiedOn");
            if (ModelState.IsValid)
            {
                ProjectsDones projectsDonesEdit = projectDoneManager.Find(x => x.Id == projectsDones.Id);
                if (Image1 != null &&
                      (Image1.ContentType == "image/jpeg" ||
                       Image1.ContentType == "image/jpg" ||
                       Image1.ContentType == "image/png"))
                {
                    string filename1 = $"{projectsDones.ProjectName}_Image1.{Image1.ContentType.Split('/')[1]}";
                    Image1.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename1}"));
                    projectsDonesEdit.Image1 = filename1;
                }
                if (Image2 != null &&
                      (Image2.ContentType == "image/jpeg" ||
                       Image2.ContentType == "image/jpg" ||
                       Image2.ContentType == "image/png"))
                {
                    string filename2 = $"{projectsDones.ProjectName}_Image2.{Image2.ContentType.Split('/')[1]}";
                    Image2.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename2}"));
                    projectsDonesEdit.Image2 = filename2;
                }
                if (Image3 != null &&
                      (Image3.ContentType == "image/jpeg" ||
                       Image3.ContentType == "image/jpg" ||
                       Image3.ContentType == "image/png"))
                {
                    string filename3 = $"{projectsDones.ProjectName}_Image3.{Image3.ContentType.Split('/')[1]}";
                    Image3.SaveAs(Server.MapPath($"~/Image/projectsdone/{filename3}"));
                    projectsDonesEdit.Image3 = filename3;
                }

                projectsDonesEdit.ProjectName = projectsDones.ProjectName;
                projectsDonesEdit.ServicesId = projectsDones.ServicesId;
                projectsDonesEdit.Teknologies = projectsDones.Teknologies;
                projectsDonesEdit.Description = projectsDones.Description;
                projectsDonesEdit.ProjectDoneDate = projectsDones.ProjectDoneDate;
                projectsDonesEdit.Customer = projectsDones.Customer;
                projectDoneManager.Update(projectsDonesEdit);
                return RedirectToAction("Index");
            }
            ViewBag.ServicesId = new SelectList(serviceManager.List(), "Id", "Title", projectsDones.ServicesId);
            return View(projectsDones);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            ProjectsDones projectsDone = projectDoneManager.Find(x => x.Id == id.Value);
            if (projectsDone != null)
            {
                int res = projectDoneManager.Delete(projectsDone);
                if (res > 0)
                {
                    System.IO.File.Delete(Server.MapPath($"~/Images/projectsdone/{projectsDone.ProjectName}_Image1"));
                    System.IO.File.Delete(Server.MapPath($"~/Images/projectsdone/{projectsDone.ProjectName}_Image2"));
                    System.IO.File.Delete(Server.MapPath($"~/Images/projectsdone/{projectsDone.ProjectName}_Image3"));
                    return Json(new { hasError = false, Message = $"{ projectsDone.ProjectName }" + " adlı proje başarılı bir şekilde silindi." }, JsonRequestBehavior.AllowGet);
                    //return Json(new { hasError = false, Massage = "Personel başarılı bir şekilde silindi." });
                }
                else
                {
                    return Json(new { hasError = true, Message = $"{ projectsDone.ProjectName }" + " adlı proje silinirken hata oluştu." }, JsonRequestBehavior.AllowGet);
                    //return Json(new { hasError = true, Message = "Personel silinirken hata oluştu." });
                }
            }
            return Json(new { results = true, Message = $"{ projectsDone.ProjectName }" + " adlı bir personel bulunamadı." }, JsonRequestBehavior.AllowGet);
        }
    }
}

MvcPersonalProject.UI/Views/ProjectDone/Create.cshtml
@using MvcPersonalProject.Entity
@model ProjectsDones
@{
    ViewBag.Title = "Yeni Proje";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Create", "ProjectDone", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(false)

                <div class="form-group row">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image1, htmlAttributes: new { @class = "control-label" })
                        <input type="file" name="Image1" id="Image1" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                        <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                        <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image2, htmlAttributes: new { @class = "control-label col-md-2" })
                        <input type="file" name="Image2" id="Image2" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                        <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                        <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image3, htmlAttributes: new { @class = "control-label col-md-2" })
                        <input type="file" name="Image3" id="Image3" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                        <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                        <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Services.Title, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.ServicesId,(SelectList)ViewBag.ServicesList, "Lütfen hizmet alanını seçiniz", new { @class = "dropdown form-control" })
                        @*@Html.DropDownList("ServicesId", (IEnumerable<SelectListItem>)ViewBag.ServicesId, new { @class = "dropdown form-control" })*@
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Teknologies, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Teknologies, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Customer, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        <textarea name="Description" class="ckeditor form-control"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.ProjectDoneDate, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ProjectDoneDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        <button type="submit" class="btn btn-success"> <i class="fa fa-save mr-2"></i>Kaydet</button>
                        <a href="/ProjectDone/Index" class="btn btn-danger"><i class="fa fa-angle-double-left mr-2"></i>İptal</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MvcPersonalProject.UI/Views/ProjectDone/Details.cshtml
@using MvcPersonalProject.Entity
@model ProjectsDones
@{
    ViewBag.Title = "Detay";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <dl class="dl-horizontal">

            <div class="row">
                <div class="col-md-4">
                    <dd>
                        <img src="~/Image/projectsdone/@Model.Image1" alt="" width="150" height="150" class="img-fluid img-responsive" />
                    </dd>
                </div>
                <div class="col-md-4">
                    <dd>
                        <img src="~/Image/projectsdone/@Model.Image2" alt="" width="150" height="150" class="img-fluid img-responsive" />
                    </dd>
                </div>
                <div class="col-md-4">
                    <dd>
                        <img src="~/Image/projectsdone/@Model.Image3" alt="" width="150" height="150" class="img-fluid img-responsive" />
                    </dd>
                </div>
            </div>

            <dt>
                @Html.DisplayNameFor(model => model.ProjectName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProjectName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Services.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Services.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Teknologies)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Teknologies)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Customer)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Customer)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.Raw(Model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProjectDoneDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProjectDoneDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ModifiedOn)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ModifiedOn)
            </dd>

        </dl>
    </div>
</div>
<div class="col-md-12 text-right">
    <a href="/ProjectDone/Edit/@Model.Id" class="btn btn-warning" title="Güncelle"><span class="glyphicon glyphicon-edit mr-2"></span> Güncelle</a>
    <a href="/ProjectDone/Index" class="btn btn-default" title="Geri Dön"><span class="glyphicon glyphicon-arrow-left mr-2"></span> Geri Dön</a>
</div>

MvcPersonalProject.UI/Views/ProjectDone/Edit.cshtml
@using MvcPersonalProject.Entity
@model ProjectsDones
@{
    ViewBag.Title = "Güncelleme";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Edit", "ProjectDone", FormMethod.Post, new { @enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(false)
                @Html.HiddenFor(model => model.Id)
                <div class="form-group row">
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image1, htmlAttributes: new { @class = "control-label" })
                        <img src="~/Image/projectsdone/@Model.Image1" class="img-responsive img-rounded mb-2" width="128" height="128" alt="" />
                        @*@Html.HiddenFor(model => model.Image1)*@
                        <div class="custom-file">
                            <input type="file" name="Image1" id="Image1" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                            <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                            <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image2, htmlAttributes: new { @class = "control-label" })
                        <img src="~/Image/projectsdone/@Model.Image2" class="img-responsive img-rounded mb-2" width="128" height="128" alt="" />
                        @*@Html.HiddenFor(model => model.Image2)*@
                        <div class="custom-file">
                            <input type="file" name="Image2" id="Image2" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                            <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                            <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.Image3, htmlAttributes: new { @class = "control-label" })
                        <img src="~/Image/projectsdone/@Model.Image3" class="img-responsive img-rounded mb-2" width="128" height="128" alt="" />
                        @*@Html.HiddenFor(model => model.Image3)*@
                        <div class="custom-file">
                            <input type="file" name="Image3" id="Image3" class="form-control" accept=".png,.jpg,.jpeg" /><br />
                            <span class="glyphico glyphicon-info-sign">&nbsp;</span>
                            <span><i>Lütfen .png,.jpeg ya da .jpg formatı kullanın</i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Services.Title, htmlAttributes: new { @class = "control-label" })
                        @Html.DropDownListFor(m => m.ServicesId, (SelectList)ViewBag.ServicesId, "Lütfen hizmet alanını seçiniz", new { @class = "dropdown form-control pull-right" })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Teknologies, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Teknologies, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Customer, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.Customer, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                        <textarea name="Description" class="ckeditor form-control">@Model.Description</textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        @Html.LabelFor(model => model.ProjectDoneDate, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.ProjectDoneDate, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-10 offset-1">
                        <button type="submit" class="btn btn-success"> <i class="fa fa-save mr-2"></i>Kaydet</button>
                        <a href="/ProjectDone/Index" class="btn btn-danger"><i class="fa fa-angle-double-left mr-2"></i>İptal</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MvcPersonalProject.UI/Views/ProjectDone/Index.cshtml
@using MvcPersonalProject.Entity
@model IEnumerable<ProjectsDones>
@{
    ViewBag.Title = "Yapılan Projeler";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="display-4">
            @ViewBag.Title
            <hr />
        </div>
    </div>
</div>
<p>
    <a href="/ProjectDone/Create" class="btn btn-primary" title="Yeni Deneyim Ekle"> <i class="fa fa-plus"></i> Yeni Proje Ekle</a>
</p>
<table class="table table-bordered table-striped table-hover table-sm" id="projectDoneTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Services.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Teknologies)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectDoneDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Services.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Teknologies)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Customer)
            </td>
            <td>
                @Html.Raw(item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectDoneDate)
            </td>
            <td>
                <a href="/ProjectDone/Edit/@item.Id" title="Güncelle" class="btn btn-warning"><i class="fa fa-edit mr-2"> Güncelle</i></a>
                <a href="/ProjectDone/Details/@item.Id" title="Detay" class="btn btn-default"> <i class="fa fa-search mr-2"> Detay</i></a>
                <a title="Sil" class="btn btn-danger projectDoneDelete" data-id="@item.Id"> <i class="fa fa-trash-o mr-2"> Sil</i></a>
            </td>
        </tr>
    }

</table>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/customDelete.js"></script>